version: '2.2'
services:
  icecast:
    image: libretime/icecast:2.4.4
    environment:
      - ICECAST_SOURCE_PASSWORD=hackme!
      - ICECAST_ADMIN_EMAIL=ricksterhd123@gmail.com
      - ICECAST_ADMIN_USERNAME=admin
      - ICECAST_ADMIN_PASSWORD=hackme!
    ports:
      - 8000:8000

  rbstream:
    build: .
    environment:
      - ICECAST2_HOST=icecast
      - ICECAST2_PORT=8000
      - ICECAST2_SOURCE_PASSWORD=hackme!
      - ICECAST2_SOURCE_MOUNT=/stream
    depends_on:
      - icecast
